# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 14, 5, 42, 33, 707661, tzinfo=utc)),
        ),
    ]
