# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcheck', '0003_auto_20170914_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='ms',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
